# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Reorder presentations

# Attribute name
nameFrom: name

# Model Class name
modelClass: Waka\Tbser\Models\Presentation

# Toolbar widget configuration
#toolbar:
    # Partial for toolbar buttons
    # buttons: reorder_toolbar